version: "2.4"
services:
  postgres-db-demo:
    image: postgres:latest
    container_name: postgres-db-demo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: pactdb-demo

  pact-broker-demo:
    image: pactfoundation/pact-broker:latest
    container_name: pact-broker-demo
    depends_on:
      - postgres-db-demo
    ports:
      - "9293:9292"
    environment:
      PACT_BROKER_DATABASE_URL: "postgres://user1:pass1@postgres-db-demo/pactdb-demo"